service: herd

image: gaurav2330/herd

servers:
  web:
    - 204.168.248.41

proxy:
  ssl: true
  host: play-herd.com
  app_port: 3000

registry:
  username: gaurav2330
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    SOLID_QUEUE_IN_PUMA: 1
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL

accessories:
  db:
    image: postgres:16
    host: 204.168.248.41
    port: 5432
    env:
      clear:
        POSTGRES_DB: herd_production
        POSTGRES_USER: herd
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data

ssh:
  keys:
    - ~/.ssh/id_ed25519_personal